### PR TITLE
refactor: tag_object param order

### PR DESCRIPTION
**Pull request by rpenido**
## Description

This PR changes the param order in the `tag_content` function and the tests accordingly.
PS: all function calls at `edx-platform` use named parameters, so this PR doesn't impact there.

## Testing Instructions

* Please ensure that the tests cover the expected behavior

___
Private ref: [FAL-3621](https://tasks.opencraft.com/browse/FAL-3621)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @rpenido! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by bradenmacdonald — APPROVED** [review]
Nice, thank you ❤️

**Comment by bradenmacdonald** [comment]
Does this break anything in edx-platform though? Will we have to make corresponding changes on that side before bumping the version?

**Comment by rpenido** [comment]
> Does this break anything in edx-platform though? Will we have to make corresponding changes on that side before bumping the version?

No. All calls from `` edx-platform `   use named parameters.

**Comment by openedx-webhooks** [comment]
@rpenido 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-learning&entry.867055334=https://github.com/openedx/openedx-learning/pull/165&entry.1484655318=https://github.com/rpenido&entry.752974735=2024-02-21+20:48&entry.1917517419=2024-02-23+19:02&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
