### PR TITLE
feat: Changes to build Taxonomy List page [FC-0036]

### PR DESCRIPTION
**Pull request by ChrisChV**
**Changes added:**

* Authentication classes added to tagging API views. This is so that calls from the MFE are correctly authenticated
* Cast taxonomies before serialize in TaxonomySerializer
* Test updated

**Testing instructions**

- Verify that the behaviour of the tests is unchanged
- Test this changes on https://github.com/openedx/edx-platform/pull/33439 and https://github.com/openedx/frontend-app-course-authoring/pull/622

**After merge**

- Bump a version

**Internal ticket:** [FAL-3522](https://tasks.opencraft.com/browse/FAL-3522)
**Github issue:** https://github.com/openedx/modular-learning/issues/104

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ChrisChV!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by rpenido — APPROVED** [review]
I have nothing to add.
Good work here @ChrisChV!

We should just track the PRs merging order to bump the version.

@bradenmacdonald Could you take a look here as CC reviewer?

**Comment by openedx-webhooks** [comment]
@ChrisChV 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-learning&entry.867055334=https://github.com/openedx/openedx-learning/pull/98&entry.1484655318=https://github.com/ChrisChV&entry.752974735=2023-10-12+21:32&entry.1917517419=2023-10-13+16:43&entry.2133058324=Yes) so we can improve your experience in the future.

**Review by bradenmacdonald — COMMENTED** [review]
Nice work! Approved 👍🏻

**Pull request merged**
